### ISSUE TITLE
Porting to a different radio?  ttgolora32. ?

### ISSUE THREAD

**Issue by richardctrimble** [JNSwanson/ESP-Home-iBoost#18]
Hi 
I was thinking, would it be technically possible to port to a device like this? 
 https://www.aliexpress.com/item/32872078587.html if I got the 868 version..

its nice with esp32 and built in screen?  possibly over kill?  

question if it is even worth trying?

Rich

**Comment by JNSwanson** [comment]
I have played around with these and the radios are LoRa specific. I have used a Lilygo T-PicoC3 as a MQTT monitor. I will publish the code if you are interested. ![image](https://github.com/user-attachments/assets/34acdf05-615f-4c9e-89d1-f4563cee4959)

**Comment by richardctrimble** [comment]
I was looking at them as I found this project https://docs.openmqttgateway.com/setitup/rf.html#protocols-modules-and-library that seems to be able to rtl_433 on it?  but in recipe only,  but im not sure why receive only mode.   Is that direct to mqtt?  I did a similar screen, but it's just esp home to home assistant so nothing that custom.  or clever.

**Comment by JNSwanson** [comment]
RTL_433 only supports receive.
The T-PicoC3 is a RP2040 and ESP32-C3 on the same board.  The ESP supports the WiFi and the RP supports the display.  They communicate serially via AT commands.  It connects the the MQTT server on HA to get the data and display it.  To get ESPHome devices to send to the MQTT server, you need to add this in the yaml file (but it is not in json format):
```
mqtt:
  topic_prefix: "iBoost"
  discovery: false
  broker: 192.168.0.30      <- address of the HA server
  port: 1883
  username: "mqtt_user"   <- you need to create this user on HA
  password: "yourPassword"
  discovery_prefix: homeassistant
```
Then use something like MQTT Explorer to look at the format.  You obv. need to add the  Mosquitto Broker as an add on in HA.
